# Generated by Django 3.1.5 on 2021-01-27 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('cod_ciudad', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cod_persona', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('cedula', models.PositiveSmallIntegerField(max_length=8)),
                ('fehca_nac', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('tel_cel', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=20)),
                ('tipo_persona', models.CharField(choices=[('F', 'Fisica'), ('J', 'Juridica')], default='F', max_length=1)),
                ('cod_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.ciudad')),
            ],
        ),
    ]
