# Generated by Django 3.1.5 on 2021-01-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
