# Generated by Django 3.1.5 on 2021-02-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0002_auto_20210127_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.EmailField(max_length=100),
        ),
    ]
