# Generated by Django 3.1.5 on 2021-02-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0003_auto_20210202_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(max_length=20),
        ),
    ]
