# Generated by Django 3.1.5 on 2021-02-04 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0004_auto_20210203_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='cod_ciudad',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='descripcion',
            field=models.CharField(max_length=30, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(max_length=20, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cod_ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.ciudad', verbose_name='Código Ciudad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cod_persona',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres',
            field=models.CharField(max_length=20, verbose_name='Nombres'),
        ),
        migrations.AlterModelTable(
            name='ciudad',
            table='ciudad',
        ),
        migrations.AlterModelTable(
            name='persona',
            table='persona',
        ),
    ]
