# Generated by Django 3.1.5 on 2021-02-04 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0005_auto_20210203_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='fehca_nac',
            new_name='fecha_nac',
        ),
    ]
